# VERSATIL Framework v3.0.0 - Helm Values
# Default values for Kubernetes deployment

replicaCount: 3

image:
  repository: versatil-sdlc-framework
  pullPolicy: IfNotPresent
  tag: "3.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: versatil-framework.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: versatil-tls
      hosts:
        - versatil-framework.local

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# BMAD Agents Configuration
agents:
  mariaQA:
    enabled: true
    replicas: 2
  marcusBackend:
    enabled: true
    replicas: 2
  jamesFrontend:
    enabled: true
    replicas: 1
  sarahPM:
    enabled: true
    replicas: 1

# PostgreSQL Configuration
postgresql:
  enabled: true
  auth:
    username: versatil
    password: versatil
    database: versatil
  primary:
    persistence:
      enabled: true
      size: 10Gi

# Redis Configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 5Gi

# Environment Variables
env:
  NODE_ENV: "production"
  VERSATIL_HOME: "/app"