{
  "language": "en-US",
  "early_access": false,
  "reviews": {
    "profile": "chill",
    "request_changes_workflow": false,
    "high_level_summary": true,
    "poem": true,
    "review_status": true,
    "collapse_walkthrough": false,
    "auto_review": {
      "enabled": true,
      "drafts": false,
      "base_branches": [
        "main",
        "master",
        "develop"
      ]
    }
  },
  "chat": {
    "auto_reply": true
  },
  "tone_instructions": "\nYou are reviewing code for the VERSATIL SDLC Framework, an AI-native development framework.\nFocus on:\n1. Code quality and maintainability\n2. TypeScript best practices\n3. Agent coordination patterns\n4. Rule integration compliance\n5. Performance optimization\n6. Security considerations\n7. Documentation completeness\n\nBe constructive and provide specific suggestions for improvement.\nHighlight any violations of OPERA methodology or framework conventions.\n"
}