name: Feature Request
description: Suggest a new feature for VERSATIL
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear description of the feature
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: When and why would this be useful?
      placeholder: |
        As a [type of user], I want [feature] so that [benefit]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Agent Enhancement
        - New Agent
        - Skill Enhancement
        - New Skill
        - Wave 4 Coordination
        - RAG/Memory
        - Documentation
        - Testing
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Mockups, examples, related features
